export type Pattern = {
  id: string;
  nightlord: string;
  spawnPoint: string;
  shiftingEarth: string;
  quadrant: "TL" | "TR" | "BL" | "BR";
  camp: string | null;
};

export const PATTERNS: Pattern[] = [
  { id: "000", nightlord: "Tricephalos", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "001", nightlord: "Tricephalos", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "002", nightlord: "Tricephalos", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "003", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "004", nightlord: "Tricephalos", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "005", nightlord: "Tricephalos", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "006", nightlord: "Tricephalos", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "007", nightlord: "Tricephalos", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "008", nightlord: "Tricephalos", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Church - Rats" },
  { id: "009", nightlord: "Tricephalos", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "010", nightlord: "Tricephalos", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Church - Rats" },
  { id: "011", nightlord: "Tricephalos", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "012", nightlord: "Tricephalos", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "013", nightlord: "Tricephalos", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Wandering Nobles" },
  { id: "014", nightlord: "Tricephalos", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "015", nightlord: "Tricephalos", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "016", nightlord: "Tricephalos", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Foot Soldiers" },
  { id: "017", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "018", nightlord: "Tricephalos", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "019", nightlord: "Tricephalos", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "020", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Church - Rats" },
  { id: "021", nightlord: "Tricephalos", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "022", nightlord: "Tricephalos", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "023", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "024", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "025", nightlord: "Tricephalos", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "026", nightlord: "Tricephalos", spawnPoint: "Far Southwest", shiftingEarth: "Crater", quadrant: "BL", camp: "Small Camp - Foot Soldiers" },
  { id: "027", nightlord: "Tricephalos", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "028", nightlord: "Tricephalos", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "029", nightlord: "Tricephalos", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "030", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "031", nightlord: "Tricephalos", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Church - Rats" },
  { id: "032", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "033", nightlord: "Tricephalos", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "034", nightlord: "Tricephalos", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "035", nightlord: "Tricephalos", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "036", nightlord: "Tricephalos", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Noklateo", quadrant: "BR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "037", nightlord: "Tricephalos", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "038", nightlord: "Tricephalos", spawnPoint: "Minor Erdtree", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "039", nightlord: "Tricephalos", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "040", nightlord: "Gaping Jaw", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "041", nightlord: "Gaping Jaw", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "042", nightlord: "Gaping Jaw", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "043", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "044", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "045", nightlord: "Gaping Jaw", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "046", nightlord: "Gaping Jaw", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "047", nightlord: "Gaping Jaw", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "048", nightlord: "Gaping Jaw", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "049", nightlord: "Gaping Jaw", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Church - Rats" },
  { id: "050", nightlord: "Gaping Jaw", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "051", nightlord: "Gaping Jaw", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "052", nightlord: "Gaping Jaw", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "053", nightlord: "Gaping Jaw", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "054", nightlord: "Gaping Jaw", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Church - Rats" },
  { id: "055", nightlord: "Gaping Jaw", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "056", nightlord: "Gaping Jaw", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "057", nightlord: "Gaping Jaw", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "058", nightlord: "Gaping Jaw", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Demi-Humans" },
  { id: "059", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "060", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "061", nightlord: "Gaping Jaw", spawnPoint: "Far Southwest", shiftingEarth: "Mountaintop", quadrant: "BL", camp: "Small Camp - Demi-Humans" },
  { id: "062", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "063", nightlord: "Gaping Jaw", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "064", nightlord: "Gaping Jaw", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Church - Rats" },
  { id: "065", nightlord: "Gaping Jaw", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "066", nightlord: "Gaping Jaw", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "067", nightlord: "Gaping Jaw", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "068", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "069", nightlord: "Gaping Jaw", spawnPoint: "Far Southwest", shiftingEarth: "Crater", quadrant: "BL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "070", nightlord: "Gaping Jaw", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "071", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "072", nightlord: "Gaping Jaw", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "073", nightlord: "Gaping Jaw", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "074", nightlord: "Gaping Jaw", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "075", nightlord: "Gaping Jaw", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Noklateo", quadrant: "BR", camp: "Church - Rats" },
  { id: "076", nightlord: "Gaping Jaw", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Noklateo", quadrant: "BR", camp: "Small Camp - Shack" },
  { id: "077", nightlord: "Gaping Jaw", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "078", nightlord: "Gaping Jaw", spawnPoint: "Minor Erdtree", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "079", nightlord: "Gaping Jaw", spawnPoint: "Southeast of Lake", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "080", nightlord: "Sentient Pest", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "081", nightlord: "Sentient Pest", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "082", nightlord: "Sentient Pest", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Church - Rats" },
  { id: "083", nightlord: "Sentient Pest", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "084", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "085", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "086", nightlord: "Sentient Pest", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "087", nightlord: "Sentient Pest", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "088", nightlord: "Sentient Pest", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "089", nightlord: "Sentient Pest", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "090", nightlord: "Sentient Pest", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "091", nightlord: "Sentient Pest", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "092", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "093", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "094", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "095", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "096", nightlord: "Sentient Pest", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Church - Rats" },
  { id: "097", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "098", nightlord: "Sentient Pest", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "099", nightlord: "Sentient Pest", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "100", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "101", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "102", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "103", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "104", nightlord: "Sentient Pest", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Church - Rats" },
  { id: "105", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "106", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "107", nightlord: "Sentient Pest", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "108", nightlord: "Sentient Pest", spawnPoint: "Minor Erdtree", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "109", nightlord: "Sentient Pest", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "110", nightlord: "Sentient Pest", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: "Small Camp - Shack" },
  { id: "111", nightlord: "Sentient Pest", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: "Small Camp - Foot Soldiers" },
  { id: "112", nightlord: "Sentient Pest", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: "Small Camp - Shack" },
  { id: "113", nightlord: "Sentient Pest", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "114", nightlord: "Sentient Pest", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "115", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Church - Rats" },
  { id: "116", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "117", nightlord: "Sentient Pest", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "118", nightlord: "Sentient Pest", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "119", nightlord: "Sentient Pest", spawnPoint: "Southeast of Lake", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "120", nightlord: "Augur", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "121", nightlord: "Augur", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Church - Rats" },
  { id: "122", nightlord: "Augur", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "123", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Church - Rats" },
  { id: "124", nightlord: "Augur", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "125", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Demi-Humans" },
  { id: "126", nightlord: "Augur", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "127", nightlord: "Augur", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "128", nightlord: "Augur", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "129", nightlord: "Augur", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "130", nightlord: "Augur", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "131", nightlord: "Augur", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "132", nightlord: "Augur", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "133", nightlord: "Augur", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "134", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Caravans and Nobles" },
  { id: "135", nightlord: "Augur", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "136", nightlord: "Augur", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Caravans and Nobles" },
  { id: "137", nightlord: "Augur", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "138", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "139", nightlord: "Augur", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "140", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Mountaintop", quadrant: "BL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "141", nightlord: "Augur", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "142", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Mountaintop", quadrant: "BL", camp: "Small Camp - Wandering Nobles" },
  { id: "143", nightlord: "Augur", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "144", nightlord: "Augur", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "145", nightlord: "Augur", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "146", nightlord: "Augur", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "147", nightlord: "Augur", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "148", nightlord: "Augur", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "149", nightlord: "Augur", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "150", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: "Church - Rats" },
  { id: "151", nightlord: "Augur", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "152", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: "Small Camp - Demi-Humans" },
  { id: "153", nightlord: "Augur", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Church - Rats" },
  { id: "154", nightlord: "Augur", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "155", nightlord: "Augur", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "156", nightlord: "Augur", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "157", nightlord: "Augur", spawnPoint: "Southeast of Lake", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "158", nightlord: "Augur", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Noklateo", quadrant: "BR", camp: "Church - Rats" },
  { id: "159", nightlord: "Augur", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "160", nightlord: "Equilibrious Beast", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "161", nightlord: "Equilibrious Beast", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "162", nightlord: "Equilibrious Beast", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Wandering Nobles" },
  { id: "163", nightlord: "Equilibrious Beast", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "164", nightlord: "Equilibrious Beast", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "165", nightlord: "Equilibrious Beast", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "166", nightlord: "Equilibrious Beast", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "167", nightlord: "Equilibrious Beast", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "168", nightlord: "Equilibrious Beast", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Foot Soldiers" },
  { id: "169", nightlord: "Equilibrious Beast", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "170", nightlord: "Equilibrious Beast", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Wandering Nobles" },
  { id: "171", nightlord: "Equilibrious Beast", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "172", nightlord: "Equilibrious Beast", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Foot Soldiers" },
  { id: "173", nightlord: "Equilibrious Beast", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "174", nightlord: "Equilibrious Beast", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "175", nightlord: "Equilibrious Beast", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "176", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "177", nightlord: "Equilibrious Beast", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "178", nightlord: "Equilibrious Beast", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "179", nightlord: "Equilibrious Beast", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "180", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "181", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "182", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "183", nightlord: "Equilibrious Beast", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "184", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "185", nightlord: "Equilibrious Beast", spawnPoint: "Minor Erdtree", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "186", nightlord: "Equilibrious Beast", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: "Church - Rats" },
  { id: "187", nightlord: "Equilibrious Beast", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "188", nightlord: "Equilibrious Beast", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "189", nightlord: "Equilibrious Beast", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "190", nightlord: "Equilibrious Beast", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: "Small Camp - Caravans and Nobles" },
  { id: "191", nightlord: "Equilibrious Beast", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: "Small Camp - Shack" },
  { id: "192", nightlord: "Equilibrious Beast", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: "Small Camp - Foot Soldiers" },
  { id: "193", nightlord: "Equilibrious Beast", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "194", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "195", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "196", nightlord: "Equilibrious Beast", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "197", nightlord: "Equilibrious Beast", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Church - Rats" },
  { id: "198", nightlord: "Equilibrious Beast", spawnPoint: "Southeast of Lake", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "199", nightlord: "Equilibrious Beast", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Church - Rats" },
  { id: "200", nightlord: "Darkdrift Knight", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "201", nightlord: "Darkdrift Knight", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "202", nightlord: "Darkdrift Knight", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "203", nightlord: "Darkdrift Knight", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Foot Soldiers" },
  { id: "204", nightlord: "Darkdrift Knight", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "205", nightlord: "Darkdrift Knight", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "206", nightlord: "Darkdrift Knight", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "207", nightlord: "Darkdrift Knight", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "208", nightlord: "Darkdrift Knight", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "209", nightlord: "Darkdrift Knight", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "210", nightlord: "Darkdrift Knight", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "211", nightlord: "Darkdrift Knight", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Caravans and Nobles" },
  { id: "212", nightlord: "Darkdrift Knight", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Wandering Nobles" },
  { id: "213", nightlord: "Darkdrift Knight", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "214", nightlord: "Darkdrift Knight", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "215", nightlord: "Darkdrift Knight", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "216", nightlord: "Darkdrift Knight", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "217", nightlord: "Darkdrift Knight", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "218", nightlord: "Darkdrift Knight", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Church - Rats" },
  { id: "219", nightlord: "Darkdrift Knight", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "220", nightlord: "Darkdrift Knight", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Mountaintop", quadrant: "BR", camp: "Small Camp - Wandering Nobles" },
  { id: "221", nightlord: "Darkdrift Knight", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "222", nightlord: "Darkdrift Knight", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "223", nightlord: "Darkdrift Knight", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "224", nightlord: "Darkdrift Knight", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Church - Rats" },
  { id: "225", nightlord: "Darkdrift Knight", spawnPoint: "Far Southwest", shiftingEarth: "Crater", quadrant: "BL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "226", nightlord: "Darkdrift Knight", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "227", nightlord: "Darkdrift Knight", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Crater", quadrant: "TL", camp: "Church - Rats" },
  { id: "228", nightlord: "Darkdrift Knight", spawnPoint: "Far Southwest", shiftingEarth: "Crater", quadrant: "BL", camp: "Small Camp - Demi-Humans" },
  { id: "229", nightlord: "Darkdrift Knight", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "230", nightlord: "Darkdrift Knight", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "231", nightlord: "Darkdrift Knight", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "232", nightlord: "Darkdrift Knight", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "233", nightlord: "Darkdrift Knight", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "234", nightlord: "Darkdrift Knight", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Caravans and Nobles" },
  { id: "235", nightlord: "Darkdrift Knight", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "236", nightlord: "Darkdrift Knight", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "237", nightlord: "Darkdrift Knight", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "238", nightlord: "Darkdrift Knight", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "239", nightlord: "Darkdrift Knight", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "240", nightlord: "Fissure in the Fog", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Wandering Nobles" },
  { id: "241", nightlord: "Fissure in the Fog", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Shack" },
  { id: "242", nightlord: "Fissure in the Fog", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "243", nightlord: "Fissure in the Fog", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Foot Soldiers" },
  { id: "244", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "245", nightlord: "Fissure in the Fog", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Church - Rats" },
  { id: "246", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "247", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "248", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "249", nightlord: "Fissure in the Fog", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Shack" },
  { id: "250", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "251", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "252", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "253", nightlord: "Fissure in the Fog", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "254", nightlord: "Fissure in the Fog", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "255", nightlord: "Fissure in the Fog", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Shack" },
  { id: "256", nightlord: "Fissure in the Fog", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "257", nightlord: "Fissure in the Fog", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Wandering Nobles" },
  { id: "258", nightlord: "Fissure in the Fog", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "259", nightlord: "Fissure in the Fog", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "260", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "261", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "262", nightlord: "Fissure in the Fog", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Mountaintop", quadrant: "BR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "263", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "264", nightlord: "Fissure in the Fog", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "265", nightlord: "Fissure in the Fog", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "266", nightlord: "Fissure in the Fog", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "267", nightlord: "Fissure in the Fog", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Church - Rats" },
  { id: "268", nightlord: "Fissure in the Fog", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Crater", quadrant: "TR", camp: "Church - Rats" },
  { id: "269", nightlord: "Fissure in the Fog", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "270", nightlord: "Fissure in the Fog", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "271", nightlord: "Fissure in the Fog", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "272", nightlord: "Fissure in the Fog", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: "Small Camp - Foot Soldiers" },
  { id: "273", nightlord: "Fissure in the Fog", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "274", nightlord: "Fissure in the Fog", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "275", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Church - Rats" },
  { id: "276", nightlord: "Fissure in the Fog", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "277", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Church - Rats" },
  { id: "278", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "279", nightlord: "Fissure in the Fog", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Noklateo", quadrant: "BR", camp: "Small Camp - Demi-Humans" },
  { id: "280", nightlord: "Night Aspect", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "281", nightlord: "Night Aspect", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "282", nightlord: "Night Aspect", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "283", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Wandering Nobles" },
  { id: "284", nightlord: "Night Aspect", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Caravans and Nobles" },
  { id: "285", nightlord: "Night Aspect", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Foot Soldiers" },
  { id: "286", nightlord: "Night Aspect", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "287", nightlord: "Night Aspect", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "288", nightlord: "Night Aspect", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Church - Rats" },
  { id: "289", nightlord: "Night Aspect", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Shack" },
  { id: "290", nightlord: "Night Aspect", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "291", nightlord: "Night Aspect", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "292", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Caravans and Nobles" },
  { id: "293", nightlord: "Night Aspect", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "294", nightlord: "Night Aspect", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: "Church - Rats" },
  { id: "295", nightlord: "Night Aspect", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "296", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Shack" },
  { id: "297", nightlord: "Night Aspect", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "298", nightlord: "Night Aspect", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "299", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "300", nightlord: "Night Aspect", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Mountaintop", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "301", nightlord: "Night Aspect", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "302", nightlord: "Night Aspect", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "303", nightlord: "Night Aspect", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: "Small Camp - Demi-Humans" },
  { id: "304", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Mountaintop", quadrant: "BR", camp: "Small Camp - Caravans and Nobles" },
  { id: "305", nightlord: "Night Aspect", spawnPoint: "Far Southwest", shiftingEarth: "Crater", quadrant: "BL", camp: "Small Camp - Caravans and Nobles" },
  { id: "306", nightlord: "Night Aspect", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "307", nightlord: "Night Aspect", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: "Small Camp - Nobles and Soldiers" },
  { id: "308", nightlord: "Night Aspect", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: "Small Camp - Demi-Humans" },
  { id: "309", nightlord: "Night Aspect", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: "Church - Rats" },
  { id: "310", nightlord: "Night Aspect", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "311", nightlord: "Night Aspect", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Church - Rats" },
  { id: "312", nightlord: "Night Aspect", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Shack" },
  { id: "313", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: "Small Camp - Shack" },
  { id: "314", nightlord: "Night Aspect", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: "Small Camp - Foot Soldiers" },
  { id: "315", nightlord: "Night Aspect", spawnPoint: "Minor Erdtree", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Nobles and Soldiers" },
  { id: "316", nightlord: "Night Aspect", spawnPoint: "Minor Erdtree", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "317", nightlord: "Night Aspect", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Wandering Nobles" },
  { id: "318", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Noklateo", quadrant: "BR", camp: "Small Camp - Rats and Demi-Humans" },
  { id: "319", nightlord: "Night Aspect", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Noklateo", quadrant: "TR", camp: "Small Camp - Caravans and Nobles" },
  { id: "1000", nightlord: "Tricephalos", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1001", nightlord: "Tricephalos", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1002", nightlord: "Tricephalos", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1003", nightlord: "Tricephalos", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1004", nightlord: "Tricephalos", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1005", nightlord: "Tricephalos", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1006", nightlord: "Tricephalos", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1007", nightlord: "Tricephalos", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1008", nightlord: "Tricephalos", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1009", nightlord: "Tricephalos", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1010", nightlord: "Gaping Jaw", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1011", nightlord: "Gaping Jaw", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1012", nightlord: "Gaping Jaw", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1013", nightlord: "Gaping Jaw", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1014", nightlord: "Gaping Jaw", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1015", nightlord: "Gaping Jaw", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1016", nightlord: "Gaping Jaw", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1017", nightlord: "Gaping Jaw", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1018", nightlord: "Gaping Jaw", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1019", nightlord: "Gaping Jaw", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1020", nightlord: "Sentient Pest", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1021", nightlord: "Sentient Pest", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1022", nightlord: "Sentient Pest", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1023", nightlord: "Sentient Pest", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1024", nightlord: "Sentient Pest", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1025", nightlord: "Sentient Pest", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1026", nightlord: "Sentient Pest", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1027", nightlord: "Sentient Pest", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1028", nightlord: "Sentient Pest", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1029", nightlord: "Sentient Pest", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1030", nightlord: "Augur", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1031", nightlord: "Augur", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1032", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1033", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1034", nightlord: "Augur", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1035", nightlord: "Augur", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1036", nightlord: "Augur", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1037", nightlord: "Augur", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1038", nightlord: "Augur", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1039", nightlord: "Augur", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1040", nightlord: "Equilibrious Beast", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1041", nightlord: "Equilibrious Beast", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1042", nightlord: "Equilibrious Beast", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1043", nightlord: "Equilibrious Beast", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1044", nightlord: "Equilibrious Beast", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1045", nightlord: "Equilibrious Beast", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1046", nightlord: "Equilibrious Beast", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1047", nightlord: "Equilibrious Beast", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1048", nightlord: "Equilibrious Beast", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1049", nightlord: "Equilibrious Beast", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1050", nightlord: "Darkdrift Knight", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1051", nightlord: "Darkdrift Knight", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1052", nightlord: "Darkdrift Knight", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1053", nightlord: "Darkdrift Knight", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1054", nightlord: "Darkdrift Knight", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1055", nightlord: "Darkdrift Knight", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1056", nightlord: "Darkdrift Knight", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1057", nightlord: "Darkdrift Knight", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1058", nightlord: "Darkdrift Knight", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1059", nightlord: "Darkdrift Knight", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1060", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1061", nightlord: "Fissure in the Fog", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1062", nightlord: "Fissure in the Fog", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1063", nightlord: "Fissure in the Fog", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1064", nightlord: "Fissure in the Fog", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1065", nightlord: "Fissure in the Fog", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1066", nightlord: "Fissure in the Fog", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1067", nightlord: "Fissure in the Fog", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1068", nightlord: "Fissure in the Fog", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1069", nightlord: "Fissure in the Fog", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1070", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1071", nightlord: "Night Aspect", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1072", nightlord: "Night Aspect", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1073", nightlord: "Night Aspect", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1074", nightlord: "Night Aspect", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1075", nightlord: "Night Aspect", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1076", nightlord: "Night Aspect", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1077", nightlord: "Night Aspect", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1078", nightlord: "Night Aspect", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1079", nightlord: "Night Aspect", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1080", nightlord: "Balancers", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1081", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1082", nightlord: "Balancers", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1083", nightlord: "Balancers", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1084", nightlord: "Balancers", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1085", nightlord: "Balancers", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1086", nightlord: "Balancers", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1087", nightlord: "Balancers", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1088", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1089", nightlord: "Balancers", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1090", nightlord: "Balancers", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1091", nightlord: "Balancers", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1092", nightlord: "Balancers", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1093", nightlord: "Balancers", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1094", nightlord: "Balancers", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1095", nightlord: "Balancers", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1096", nightlord: "Balancers", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1097", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Default", quadrant: "BL", camp: null },
  { id: "1098", nightlord: "Balancers", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1099", nightlord: "Balancers", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1100", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Mountaintop", quadrant: "BL", camp: null },
  { id: "1101", nightlord: "Balancers", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: null },
  { id: "1102", nightlord: "Balancers", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Mountaintop", quadrant: "TL", camp: null },
  { id: "1103", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Mountaintop", quadrant: "BL", camp: null },
  { id: "1104", nightlord: "Balancers", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Mountaintop", quadrant: "TR", camp: null },
  { id: "1105", nightlord: "Balancers", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: null },
  { id: "1106", nightlord: "Balancers", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Crater", quadrant: "TR", camp: null },
  { id: "1107", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Crater", quadrant: "BL", camp: null },
  { id: "1108", nightlord: "Balancers", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Crater", quadrant: "TL", camp: null },
  { id: "1109", nightlord: "Balancers", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: null },
  { id: "1110", nightlord: "Balancers", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: null },
  { id: "1111", nightlord: "Balancers", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Rotted Woods", quadrant: "BR", camp: null },
  { id: "1112", nightlord: "Balancers", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: null },
  { id: "1113", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: null },
  { id: "1114", nightlord: "Balancers", spawnPoint: "Far Southwest", shiftingEarth: "Rotted Woods", quadrant: "BL", camp: null },
  { id: "1115", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1116", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1117", nightlord: "Balancers", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1118", nightlord: "Balancers", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1119", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1120", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1121", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1122", nightlord: "Balancers", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1123", nightlord: "Balancers", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1124", nightlord: "Balancers", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1125", nightlord: "Balancers", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1126", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1127", nightlord: "Balancers", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1128", nightlord: "Balancers", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1129", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1130", nightlord: "Balancers", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1131", nightlord: "Balancers", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1132", nightlord: "Balancers", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1133", nightlord: "Balancers", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1134", nightlord: "Balancers", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1135", nightlord: "Balancers", spawnPoint: "Southeast of Lake", shiftingEarth: "Noklateo", quadrant: "TL", camp: null },
  { id: "1136", nightlord: "Balancers", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: null },
  { id: "1137", nightlord: "Balancers", spawnPoint: "Minor Erdtree", shiftingEarth: "Noklateo", quadrant: "TR", camp: null },
  { id: "1138", nightlord: "Balancers", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Noklateo", quadrant: "TR", camp: null },
  { id: "1139", nightlord: "Balancers", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Noklateo", quadrant: "TR", camp: null },
  { id: "1140", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1141", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1142", nightlord: "Dreglord", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1143", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1144", nightlord: "Dreglord", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1145", nightlord: "Dreglord", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1146", nightlord: "Dreglord", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1147", nightlord: "Dreglord", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1148", nightlord: "Dreglord", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1149", nightlord: "Dreglord", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1150", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1151", nightlord: "Dreglord", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1152", nightlord: "Dreglord", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1153", nightlord: "Dreglord", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1154", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1155", nightlord: "Dreglord", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Default", quadrant: "BR", camp: null },
  { id: "1156", nightlord: "Dreglord", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1157", nightlord: "Dreglord", spawnPoint: "Minor Erdtree", shiftingEarth: "Default", quadrant: "TR", camp: null },
  { id: "1158", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1159", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Default", quadrant: "TL", camp: null },
  { id: "1160", nightlord: "Dreglord", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Mountaintop", quadrant: "TL", camp: null },
  { id: "1161", nightlord: "Dreglord", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Mountaintop", quadrant: "TL", camp: null },
  { id: "1162", nightlord: "Dreglord", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Mountaintop", quadrant: "TL", camp: null },
  { id: "1163", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Mountaintop", quadrant: "TL", camp: null },
  { id: "1164", nightlord: "Dreglord", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Mountaintop", quadrant: "BR", camp: null },
  { id: "1165", nightlord: "Dreglord", spawnPoint: "Far Southwest", shiftingEarth: "Crater", quadrant: "BL", camp: null },
  { id: "1166", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Crater", quadrant: "TL", camp: null },
  { id: "1167", nightlord: "Dreglord", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Crater", quadrant: "TL", camp: null },
  { id: "1168", nightlord: "Dreglord", spawnPoint: "Stormhill South of Gate", shiftingEarth: "Crater", quadrant: "TL", camp: null },
  { id: "1169", nightlord: "Dreglord", spawnPoint: "East of Cavalry Bridge", shiftingEarth: "Crater", quadrant: "TR", camp: null },
  { id: "1170", nightlord: "Dreglord", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: null },
  { id: "1171", nightlord: "Dreglord", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: null },
  { id: "1172", nightlord: "Dreglord", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: null },
  { id: "1173", nightlord: "Dreglord", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Rotted Woods", quadrant: "TL", camp: null },
  { id: "1174", nightlord: "Dreglord", spawnPoint: "Below Summonwater Hawk", shiftingEarth: "Rotted Woods", quadrant: "TR", camp: null },
  { id: "1175", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1176", nightlord: "Dreglord", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1177", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1178", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1179", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1180", nightlord: "Dreglord", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1181", nightlord: "Dreglord", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1182", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1183", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1184", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1185", nightlord: "Dreglord", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1186", nightlord: "Dreglord", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1187", nightlord: "Dreglord", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1188", nightlord: "Dreglord", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1189", nightlord: "Dreglord", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1190", nightlord: "Dreglord", spawnPoint: "Northeast", shiftingEarth: "Great Hollow", quadrant: "TR", camp: null },
  { id: "1191", nightlord: "Dreglord", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1192", nightlord: "Dreglord", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1193", nightlord: "Dreglord", spawnPoint: "Southwest", shiftingEarth: "Great Hollow", quadrant: "BL", camp: null },
  { id: "1194", nightlord: "Dreglord", spawnPoint: "South", shiftingEarth: "Great Hollow", quadrant: "BR", camp: null },
  { id: "1195", nightlord: "Dreglord", spawnPoint: "Above Stormhill Tunnel Entrance", shiftingEarth: "Noklateo", quadrant: "TL", camp: null },
  { id: "1196", nightlord: "Dreglord", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: null },
  { id: "1197", nightlord: "Dreglord", spawnPoint: "Northeast of Saintsbridge", shiftingEarth: "Noklateo", quadrant: "BR", camp: null },
  { id: "1198", nightlord: "Dreglord", spawnPoint: "Southeast of Lake", shiftingEarth: "Noklateo", quadrant: "TL", camp: null },
  { id: "1199", nightlord: "Dreglord", spawnPoint: "West of Warmaster's Shack", shiftingEarth: "Noklateo", quadrant: "TL", camp: null },
];

export const NIGHTLORDS = ["Tricephalos","Gaping Jaw","Sentient Pest","Augur","Equilibrious Beast","Darkdrift Knight","Fissure in the Fog","Night Aspect","Balancers","Dreglord"] as const;
export const SHIFTING_EARTHS = ["Default","Mountaintop","Crater","Rotted Woods","Noklateo","Great Hollow"] as const;
export const CAMPS = ["Small Camp - Demi-Humans","Small Camp - Caravans and Nobles","Small Camp - Wandering Nobles","Small Camp - Foot Soldiers","Small Camp - Rats and Demi-Humans","Church - Rats","Small Camp - Nobles and Soldiers","Small Camp - Shack"] as const;
